version: "2.4"
services:
  magentapp_uat:
    build: 
      context: ./magentapp
      network: host
    container_name: "magentapp_uat"
    ports: 
      - "3101:3001"
    environment:
      - ENV=UAT
      - TZ=Europe/Budapest

  maci_uat:
    build: 
      context: ./maci/
      network: host
      args:
        _env: uat
    container_name: "maci_uat"
    ports: 
      - "3102:3002"
    environment:
      - ENV=UAT
      - TZ=Europe/Budapest

  authservice_uat:
    build:
      network: host
      context: ./microservices/authservice
      dockerfile: Dockerfile_uat
    container_name: "authservice_uat"
    ports: 
      - "3103:8080"
    environment:
      - ENV=UAT

  mailservice_uat:
    build:
      network: host
      context: ./microservices/mailservice
      dockerfile: Dockerfile_uat
    container_name: "mailservice_uat"
    ports: 
      - "3104:8080"
    environment:
      - ENV=UAT 

  mongodb:
      image: "mongo:4.2"
      volumes:
        - "mongodb_data:/data/db"
      restart: "on-failure"

  elasticsearch:
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g -Dlog4j2.formatMsgNoLookups=true"
      bootstrap.memory_lock: "true"
      discovery.type: "single-node"
      http.host: "0.0.0.0"
      action.auto_create_index: "false"
    image: "docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "es_data:/usr/share/elasticsearch/data"
    restart: "on-failure"

  graylog:
    image: "graylog/graylog:4.2"
    depends_on:
      - elasticsearch      
      - mongodb
    entrypoint: "/usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh"
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_PASSWORD_SECRET: aba34324bb365437452332sa67s6adv7fsda6dsvgdfh67asdg8sad7asdb
      GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:12200"
      GRAYLOG_HTTP_EXTERNAL_URI: "https://ef3.telekom.intra/graylog/"
      GRAYLOG_ENABLE_CORS: "true"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      GRAYLOG_TRANSPORT_EMAIL_ENABLED: "true"
      GRAYLOG_TRANSPORT_EMAIL_HOSTNAME: "tavoktatas.telekom.intra"
      GRAYLOG_TRANSPORT_EMAIL_PORT: 25
      GRAYLOG_TRANSPORT_EMAIL_USE_AUTH: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_TLS: "false"
      GRAYLOG_TRANSPORT_EMAIL_USE_SSL: "false"
      GRAYLOG_TRANSPORT_EMAIL_SUBJECT_PREFIX: "[graylog]"
      GRAYLOG_TRANSPORT_EMAIL_FROM_EMAIL: "hr.it@telekom.hu"
    ports:
    - "12200:12200/tcp"   # Server API
    - "12201:12201/udp"   # GELF UDP
    - "12202:12202/udp"   # GELF UDP
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    restart: "on-failure"


volumes:
  mongodb_data:
  es_data:
  graylog_data:
  graylog_journal:
